name = "IPMeasures"
uuid = "d7dc6e0c-a753-11e8-227e-b362679e0b17"
authors = ["pevnak <pevnak@gmail.com>"]
version = "0.2.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ConditionalDists = "c648c4dd-c1e0-49a6-84b9-144ae7fd2468"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CUDA = "1.3"
ConditionalDists = "0.4"
Distances = "0.9"
Distributions = "0.23"
DistributionsAD = "0.6"
StatsBase = "0.32, 0.33"
julia = "1"

[extras]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Flux"]
